version: "2"
run:
  build-tags:
    - e2e
    - mage
    - ignored
  tests: false
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - exhaustruct
    - godox
    - ireturn
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/cardil/ghet/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
