name: Verify

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  verify:
    uses: knative/actions/.github/workflows/reusable-verify-codegen.yaml@main
