name: Code Style

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  style:
    uses: knative/actions/.github/workflows/style.yaml@main
